max_epochs: 1000
eval_every_epochs: 50

lr: 5e-4
weight_decay: 0.0

amp: true
non_blocking: true
find_unused_parameters: true

loss:
    _target_: torch.nn.BCEWithLogitsLoss

optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: ${trainer.lr}
    weight_decay: ${trainer.weight_decay}

lr_scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: ${trainer.max_epochs}
    eta_min: 0.0
