"""CINDER: Conditioned Implicit Neural DecodeR for dense prediction."""

from .datasets import SegmentationDataset
from .engine import (
    DiceCELoss,
    DiceLoss,
    DiceMetric,
    HausdorffDistanceMetric,
    IoUMetric,
    MaskedCrossEntropyLoss,
    MultiScaleFlipInferer,
    ObjectDiceMetric,
    ObjectF1Metric,
    ObjectHausdorffMetric,
    SampledLoss,
    SlidingWindowInferer,
    create_evaluator,
    create_trainer,
)
from .models import (
    CINDER,
    FINER,
    FUTON,
    MLP,
    RFF,
    SIREN,
    WIRE,
    BaseEncoder,
    BaseModulator,
    FUTONEncoding,
    FUTONGate,
    Gauss,
    HashEncoding,
    ListModulators,
    PositionalEncoding,
    TimmEncoder,
    WeightDisplacement,
)

__version__ = "0.1.0"

__all__ = [
    "CINDER",
    "BaseEncoder",
    "TimmEncoder",
    "MLP",
    "SIREN",
    "FINER",
    "Gauss",
    "WIRE",
    "RFF",
    "FUTON",
    "PositionalEncoding",
    "HashEncoding",
    "FUTONEncoding",
    "BaseModulator",
    "ListModulators",
    "FUTONGate",
    "WeightDisplacement",
    "SegmentationDataset",
    "create_trainer",
    "create_evaluator",
    "SampledLoss",
    "DiceLoss",
    "MaskedCrossEntropyLoss",
    "DiceCELoss",
    "DiceMetric",
    "IoUMetric",
    "HausdorffDistanceMetric",
    "ObjectF1Metric",
    "ObjectDiceMetric",
    "ObjectHausdorffMetric",
    "SlidingWindowInferer",
    "MultiScaleFlipInferer",
]
