defaults:
    - default

cinr:
    _target_: cinder.ConditionalFUTON
    basis:
        - lanczos
        - num_components: ${dataset.crop_size}
          grid_size: ${dataset.crop_size}
          bandwidth: 2
    combiner:
        - cp
        - rank: 160
    decoder:
        - mlp
        - hidden_layers: 1
