defaults:
    - default

num_classes: 1

train_datalist:
    _target_: cinder.datasets.fives.create_datalist
    root: ${path.dataset_dir}
    split: train

val_datalist:
    _target_: cinder.datasets.fives.create_datalist
    root: ${path.dataset_dir}
    split: test
