defaults:
    - default

num_classes: 1

crop_size: [480, 480]

test_section: test # testA or testB

train_datalist:
    _target_: cinder.datasets.glas.create_datalist
    root: ${path.dataset_dir}
    section: train

val_datalist:
    _target_: cinder.datasets.glas.create_datalist
    root: ${path.dataset_dir}
    section: ${dataset.test_section}
