defaults:
    - _self_
    - path: default
    - hydra: default
    - dataset: glas
    - model: futongate_relu
    - handler: [checkpoint, progress]
    - trainer: ${dataset}  # for amp, non_blocking and log_interval
    - inferer: default
    - metric: [dice, hd95]

tag: ""
phase: eval
experiment: ${hydra:runtime.choices.dataset}_${hydra:runtime.choices.model}
seed: 42
