defaults:
    - _self_
    - path: default
    - hydra: default
    - dataset: glas
    - model: futongate_relu
    - handler: [checkpoint, progress, tensorboard]
    - trainer: ${dataset}  # the dataset's trainer
    - inferer: default
    - metric: [dice, hd95]

tag: ""
phase: train
experiment: ${hydra:runtime.choices.dataset}_${hydra:runtime.choices.model}
seed: 42
